### ISSUE TITLE
Everything looks great except for the labels for hours, minutes, seconds Maybe you forgot some media query for screens

### ISSUE THREAD

**Issue by swaraj961** [siddharthsaini/clock-flutter-web#1]
![Capture](https://user-images.githubusercontent.com/43717074/91121498-8b5fc580-e6b5-11ea-9979-949b560b1762.PNG)

**Comment by siddharthsaini** [comment]
Hi @swaraj961 
You're right about the media query issue,
I wanted a time screen for my secondary monitor so I made this in a hurry.
It works fine when the browser in in full screen mode so I was kinda satisfied.
